# Generated by Django 3.0.8 on 2021-02-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210215_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommanded_len',
            field=models.IntegerField(default=0),
        ),
    ]
