# Generated by Django 3.0.8 on 2021-02-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
