# Generated by Django 3.0.8 on 2021-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_recommanded_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='level_Percentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(blank=True, max_length=100)),
                ('percentage', models.IntegerField(blank=True)),
            ],
        ),
    ]
