# Generated by Django 3.0.8 on 2021-02-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_level_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level_percentage',
            name='level_name',
            field=models.IntegerField(blank=True),
        ),
    ]
